name: search_repositories_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed: ^2.4.5
  http: ^1.1.0
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.8
  riverpod_annotation: ^2.3.2
  json_annotation: ^4.8.1
  envied: ^0.5.2
  dio: ^5.4.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  go_router: ^12.1.3
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  generate: true
arb-dir: lib/l10n
template-arb-file: app_ja.arb
output-class: L10n
output-localization-file: app_localizations.dart
